name: ssp_morocco_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib=3.9.2
  - xlsxwriter=3.1.1
  - ipykernel=6.29.5
  - pip
  - pip:
      - git+https://github.com/jcsyme/sisepuede.git@05722b11b1c15cd61a467ef3f5b270255480ab4b
      - ssp-transformations-handler==0.1.8
      - costs-benefits-ssp
      - polars
