country_name: "morocco"
ssp_input_file_name: "sisepuede_raw_inputs_latest_MAR_modified_2050.csv"
ssp_transformation_cw: "ssp_morocco_transformation_cw.xlsx"
set_lndu_reallocation_factor_to_zero: true
energy_model_flag: true